export const restsArray = [
  {
    id: 0,
    title: "Пицца плюс",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-1",
  },
  {
    id: 1,
    title: "Тануки",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-2",
  },
  {
    id: 2,
    title: "FoodBand",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-3",
  },
  {
    id: 3,
    title: "Жадина-пицца",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-4",
  },
  {
    id: 4,
    title: "Точка еды",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-5",
  },
  {
    id: 5,
    title: "PizzaBurger",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rests-6",
  },
];
